[workspace]
resolver = "2"
members = [
    "crates/pragmatic",
    "crates/pragmatic-macros",
    "crates/pragmatic-anthropic",
    "crates/pragmatic-cli",
    "crates/pragmatic-python",
    "crates/pragmatic-ffi",
    "crates/pragmatic-openai",
]

[workspace.package]
version = "0.4.0"
edition = "2021"
license = "BUSL-1.1"
repository = "https://github.com/pragmaticco/pragmaticMain"
homepage = "https://aniketh.net/pragmatic/"
readme = "README.md"
authors = ["Pragmatic Research, Inc. <me@aniketh.net>"]

[profile.release]
lto = true
codegen-units = 1
